name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > server-1.pem
          chmod 600 server-1.pem

      - name: Add EC2 server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-13-60-252-90.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Connect to EC2 and deploy
        run: |
          ssh -i "server-1.pem" ubuntu@ec2-13-60-252-90.eu-north-1.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/simple-CICD 
          git pull origin main
          npm install
          npm start
          EOF
